<template>
    <div>
        <h3>A Breif History of Time<small>--Stephen Hawking</small></h3>
        <div>
            <el-tree :data="data" :props="defaultProps" @node-click="handleNodeClick"></el-tree>
        </div>
    </div>
</template>
<script>
    export default {
        data(){
            return {
                data:[
                    {label:'前言',
                        children:[
                            {label:'前言'}
                        ]
                    },
                    {label:'第一章',
                        children:[
                            {label:'我们的宇宙图像'}
                        ]
                    },
                    {label:'第二章',children:[
                            {label:'空间和时间'}
                        ]
                    },
                    {label:'第三章',children:[
                            {label:'膨胀的宇宙'}
                        ]
                    },
                    {label:'第四章',children:[
                            {label:'不确定性原理'}
                        ]
                    },
                    {label:'第五章',children:[
                            {label:'基本粒子和自然的力'}
                        ]
                    },
                    {label:'第六章',children:[
                            {label:'黑洞'}
                        ]
                    },
                    {label:'第七章',children:[
                            {label:'黑洞不是这么黑的'}
                        ]
                    },
                    {label:'第八章',children:[
                            {label:'宇宙的起源和命运'}
                        ]
                    },
                    {label:'第九章',children:[
                            {label:'时间箭头'}
                        ]
                    },
                    {label:'第十章',children:[
                            {label:'虫洞和时间旅行'}
                        ]
                    },
                    {label:'第十一章',children:[
                            {label:'物理学的统一'}
                        ]
                    },
                    {label:'第十二章',children:[
                            {label:'结论'}
                        ]
                    }
                ]
            }
        }
    }
</script>
<style lang="less" scoped>

</style>